export const BEGIN_AJAX_READ = 'BEGIN_AJAX_READ';
export const END_AJAX_READ = 'END_AJAX_READ';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';
export const CREATE_COURSE_SUCCESS = 'CREATE_COURSE_SUCCESS';
export const UPDATED_COURSE_SUCCESS = 'UPDATED_COURSE_SUCCESS';
export const LOAD_COURSES_SUCCESS = 'LOAD_COURSES_SUCCESS';
export const LOAD_AUTHORS_SUCCESS = 'LOAD_AUTHORS_SUCCESS';
